### ISSUE TITLE
Showing past events

### ISSUE THREAD

**Issue by Danny-weebo** [punkave/apostrophe-events#6]
Hey, I'm trying to show all the past events in the `index.html`
any directions ?

thanks (:

**Comment by israelidanny** [comment]
Is this possible? We need that for a client site that wants to display past events in the widget.

**Comment by Danny-weebo** [comment]
@boutell, we are waiting for a month now for an answer, can you please give us a clue how to do it ?

**Comment by boutell** [comment]
Your original question was about past events in index.html, which is already permissible, you can browse by month. I think what you really wanted, as mentioned in a later comment, was past events in a widget. This is not currently possible. It would be a straightforward patch. Surely you've had a look at apostrophe-events/index.js by now...

**Comment by Danny-weebo** [comment]
seems like overiding index.js (of apostrophe-events) isn't working .. how can I fetch the past events ?

**Comment by boutell** [comment]
Can you clarify what you really want to do first? You can already see past events on the index page using the monthly navigation.

**Comment by Danny-weebo** [comment]
Yes, I want to show all the events (even those that was made in the past and aren't relevent anymore) in the index.html page.
and what do you mean by "monthly navigation" can you be more specific please ?

thanks!

**Comment by boutell** [comment]
A toggle to navigate by month rather than showing upcoming events is
provided in the standard templates of the events module, and all the
plumbing for it is there in index.js.

On Wed, Feb 11, 2015 at 8:27 AM, Danny Braunstein <notifications@github.com>
wrote:

> Yes, I want to show all the events (even those that was made in the past
> and aren't relevent anymore) in the index.html page.
> and what do you mean by "monthly navigation" can you be more specific
> please ?
>
> thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe-events/issues/6#issuecomment-73880288>
> .
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by Danny-weebo** [comment]
I'd prefer to to get all the events in one array, how can I overide the index.js to propertly implement this functionality?

Currently, if I put an index.js in my modules/apostrophe-events folder, all hell breaks loose. So obviously that's not the right way to go about it. :)

**Comment by boutell** [comment]
You really need to be more specific than "all hell breaks loose."

Here's an example of an index.js at project level that's working for us in
one of our projects. This one manipulates a "q" query parameter.

var _ = require('underscore');

module.exports = events;

function events(options, callback) {
  return new events.events(options, callback);
}

events.events = function(options, callback) {
  var self = this;

  module.exports.Super.call(this, options, null);

  var superAddCriteria = self.addCriteria;
  self.addCriteria = function(req, criteria, options) {
    if (req.query.q) {
      options.q = self._apos.sanitizeString(req.query.q);
      req.extras.q = options.q;
    }
    return superAddCriteria(req, criteria, options);
  };

  if (callback) {
    process.nextTick(function() { return callback(null); });
  }

};


On Wed, Feb 11, 2015 at 8:39 AM, Danny Braunstein <notifications@github.com>
wrote:

> I'd prefer to to get all the events in one array, how can I overide the
> index.js to propertly implement this functionality?
>
> Currently, if I put an index.js in my modules/apostrophe-events folder,
> all hell breaks loose. So obviously that's not the right way to go about
> it. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe-events/issues/6#issuecomment-73881868>
> .
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by jsumnersmith** [comment]
@Danny-weebo,

As an example of a query for past dates, you can look at the `addApiCriteria` method in the module's index.js. There, by checking for a date flag on incoming API requests, it  can return past or future events. We use this in the admin interface to allow users to browse past or future events. For what it's worth, the core piece of that method that gets past events is `criteria.startDate = { $lte: moment().format('YYYY-MM-DD') };` which simply manipulates the `criteria` object eventually passed to the `get` method. To get future events, simply do the same, exchanging `$lte` for '$gte`. You will also want to check set the sort option for Mongo which the addApiCriteria method exemplifies.

Best,
Joel

**Comment by Danny-weebo** [comment]
Thanks guys for the help, (@israelidanny) solved it by doing it this way
```
  self.addCriteria = function(req, criteria, options) {
    superAddCriteria.call(self, req, criteria, options);
    options.upcoming = false;
    options.sort = { startDate: -1, sortTitle: 1 };
  };
```
